spring:
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  config:
    import: 'configserver:'
  cloud:
    config:
      name: elastic-query-web-client,config-client
      username: spring_cloud_user
      password: '{cipher}55529101085801c7ec539438750728183880c15d1d26b5a6503860a2777e5349c7770d11beb469dff05a686fd709981a'

log:
  app-name: elastic-query-web-client