server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/genaldyjps/spring-cloud-config-server-repository
          default-label: master
          username: genaldyjps
          password: '{cipher}10b4b515f12a1f0b92fb8e7810bb3d5d816698d9bf5f4f0ef52bbacd0ca86c74'
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}55529101085801c7ec539438750728183880c15d1d26b5a6503860a2777e5349c7770d11beb469dff05a686fd709981a'

log:
  app-name: config-server
